### ISSUE TITLE
Server Profile After 1st Not saving

### ISSUE THREAD

**Issue by eric963** [alec-hs/Flaxs-Arma-Server-Tool-2#49] opened 2018-12-01 22:43 UTC
Created my first server profile and saved it.  Restarted fast and it was listed under server profiles.  Tried to create second profile but when reloading fast the 2nd server profile was not listed.

The folder and cfg files were created in the "Servers" folder.

**Comment by alec-hs** [comment] 2019-01-09 00:01
@eric963 I cannot reproduce this - is this still happening for you?

**Comment by eric963** [comment] 2019-01-09 01:42
I just deleted everything related to FAST2 and reinstalled and this issue is no there.
Thanks
Eric

**Comment by alec-hs** [comment] 2019-01-09 09:54
Closing - not reproducible.

**Closed by alec-hs** 2019-01-09 09:54 UTC
Labels: bug, can't reproduce
