### ISSUE TITLE
Adding "-" into the Server Profiles Name crashes the app

### ISSUE THREAD

**Issue by JamieKG** [alec-hs/Flaxs-Arma-Server-Tool-2#16] opened 2018-10-18 15:55 UTC
Adding a "-" like "test-test" will crash the app and it will not open again unless you remove the offending server profile out of the user config

**Comment by alec-hs** [comment] 2018-10-18 15:56
Will add handling of this char to the safeName function.

**Comment by JamieKG** [comment] 2018-10-18 16:18
so adding this
```                            <SafeName>test-test</SafeName>
                            <DisplayName>testtest</DisplayName>```
will result in the app not starting

**Comment by JamieKG** [comment] 2018-10-18 16:20
a "-" in safename or displayname
results in the app not starting

**Comment by alec-hs** [comment] 2018-10-18 17:34
Ok thanks, will add it to the list of no go characters once I find the cause.

**Comment by JamieKG** [comment] 2018-10-18 17:47
> Could you try this in the user config for me?
> 
> `<SafeName>test_test</SafeName>`
> `<DisplayName>test-test</DisplayName>`

that works

**Comment by alec-hs** [comment] 2018-10-18 18:02
Great, fix will be in next build.

**Closed** 2018-10-24 10:13 UTC
Labels: bug
